bundle_audit:
  name: Bundle Audit
  description: Review Gem Dependencies for Security Issues
  tags: [critical, security, dependencies, ruby, dev]
  links:
    home: https://github.com/rubysec/bundler-audit
    install: https://github.com/rubysec/bundler-audit#install
  commands:
    install: "bundle exec gem install bundler-audit"
    prepare: "bundle exec bundle-audit update"
    review: "bundle exec bundle-audit check --no-update"

tests:
  name: Minitest
  description: Unit Tests & Coverage
  tags: [ruby, tests, dev]
  summary:
    pattern: '(\d+)\s+tests?'
    label: '\1 tests'
  links:
    home:
  commands:
    review: "bundle exec rake"
  reports:
    open_on_fail: true
    local_file: coverage/index.html
    local_uri: "file:///Users/garrettdimon/Code/reviewer/coverage/index.html#_AllFiles"
  env:
    testopts: --seed=$SEED
    # coverage: false

reek:
  # skip_in_batch: true # Reek provides guidance and is generally run solo
  name: Reek
  description: Examine Ruby Classes for Code Smells
  tags: [ruby, quality, dev]
  links:
    home: https://github.com/troessner/reek
    install: https://github.com/troessner/reek#quickstart
  commands:
    install: "bundle exec gem install reek"
    review: "bundle exec reek --config .reek.yml lib/"
  files:
    flag: ""
    separator: " "
    pattern: "*.rb"
  flags:
    color:
    documentation:

flog:
  # skip_in_batch: true # Flog provides guidance and is generally run solo
  name: Flog
  description: Reports your most tortured ruby code in an easy to read pain report.
  tags: [ruby, quality, dev]
  links:
    home: https://ruby.sadi.st/Flog.html
    install: https://ruby.sadi.st/Flog.html
  commands:
    install: "bundle exec gem install flog"
    review: "bundle exec flog -g lib"
  flags:
    threshold: 10 # Percentage. i.e. Show the most concerning 10% of results
    group:
    methods-only:

flay:
  # skip_in_batch: true # Flay provides guidance and is generally run solo
  name: Flay
  description: Review ruby code for structural similarities and refactoring opportunities.
  tags: [ruby, quality, dev]
  links:
    home: https://ruby.sadi.st/Flay.html
    install: https://ruby.sadi.st/Flay.html
  commands:
    install: "bundle exec gem install flay"
    review: "bundle exec flay ./lib"
  flags:
    liberal:
    summary:

rubocop:
  name: Rubocop
  description: Review Ruby Syntax & Formatting for Consistency
  tags: [ruby, syntax, dev]
  summary:
    pattern: '(\d+)\s+offenses?'
    label: '\1 offenses'
  links:
    home: https://rubocop.org
    install: https://docs.rubocop.org/rubocop/1.13/installation.html
    ignore_syntax: https://docs.rubocop.org/rubocop/configuration.html#ignoredmethods
    disable_syntax: https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code
  commands:
    install: "bundle exec gem install rubocop"
    review: "bundle exec rubocop --parallel"
    format: "bundle exec rubocop --auto-correct"
  files:
    flag: ""
    separator: " "
    pattern: "*.rb"
  flags:
    color:

# The YARD Parser can also come in handy:
#   https://yardoc.org/types
inch:
  # skip_in_batch: true
  tags: [docs, ruby, dev]
  name: Inch
  description: Review Ruby Documentation Quality
  links:
    home: https://rrrene.org/inch/
    usage: https://www.rubydoc.info/gems/yard/file/docs/Tags.md
  commands:
    install: "bundle exec gem install inch"
    review: "bundle exec inch"

yard:
  # skip_in_batch: true
  tags: [docs, ruby, dev]
  name: Yard
  description: Generates Documentation
  links:
    home: https://yardoc.org
    usage: https://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md#using
    install: https://github.com/lsegal/yard#installing
  commands:
    install: "bundle exec gem install yard"
    prepare: "yard doc 'lib/**/*.rb'"
    review: "yard stats"
    serve: "yard server --reload && open http://0.0.0.0:8808"
    generate:
    quiet_flag: "--quiet"

alex:
  skip_in_batch: true
  tags: [language, docs]
  name: Alex
  description: Catch insensitive, inconsiderate writing
  links:
    home: https://alexjs.com
  commands:
    install: "yarn global add alex"
    review: "alex ."

# New tools for expanded testing coverage

brakeman:
  skip_in_batch: true # Requires Rails application, not applicable to gems
  name: Brakeman
  description: Static analysis security scanner for Ruby
  tags: [security, ruby, dev]
  links:
    home: https://brakemanscanner.org
    install: https://brakemanscanner.org/docs/install/
  commands:
    install: "bundle exec gem install brakeman"
    review: "bundle exec brakeman --no-pager -q"

fasterer:
  name: Fasterer
  description: Suggest performance improvements for Ruby code
  tags: [ruby, quality, performance, dev]
  links:
    home: https://github.com/DamirSvrtan/fasterer
  commands:
    install: "bundle exec gem install fasterer"
    review: "bundle exec fasterer"
  files:
    flag: ""
    separator: " "
    pattern: "*.rb"

debride:
  skip_in_batch: true # Broken on Ruby 3.4 (missing require for Racc, Timeout)
  name: Debride
  description: Find potentially unused methods and classes
  tags: [ruby, quality, dev]
  links:
    home: https://github.com/seattlerb/debride
  commands:
    install: "bundle exec gem install debride"
    review: "bundle exec debride lib/"

rubycritic:
  skip_in_batch: true # Generates HTML reports, best run manually
  name: RubyCritic
  description: Code quality analysis with HTML reports
  tags: [ruby, quality, dev]
  links:
    home: https://github.com/whitesmith/rubycritic
  commands:
    install: "bundle exec gem install rubycritic"
    review: "bundle exec rubycritic lib/ --no-browser -f console"

metric_fu:
  skip_in_batch: true # Meta-tool that runs many others, slow
  name: MetricFu
  description: Aggregate code metrics from multiple tools
  tags: [ruby, quality, dev]
  links:
    home: https://github.com/metricfu/metric_fu
  commands:
    install: "bundle exec gem install metric_fu"
    review: "bundle exec metric_fu"

yardstick:
  # skip_in_batch: true # Documentation coverage measurement
  name: Yardstick
  description: Measure YARD documentation coverage
  tags: [docs, ruby, dev]
  links:
    home: https://github.com/dkubb/yardstick
  commands:
    install: "bundle exec gem install yardstick"
    review: "bundle exec yardstick lib/"

standard:
  skip_in_batch: true # Conflicts with existing RuboCop configuration
  name: Standard
  description: Zero-configuration Ruby linter
  tags: [ruby, syntax, dev]
  links:
    home: https://github.com/standardrb/standard
  commands:
    install: "bundle exec gem install standard"
    review: "bundle exec standardrb"
    format: "bundle exec standardrb --fix"

rufo:
  skip_in_batch: true # Alternative formatter to RuboCop
  name: Rufo
  description: Ruby code formatter
  tags: [ruby, syntax, dev]
  links:
    home: https://github.com/ruby-formatter/rufo
  commands:
    install: "bundle exec gem install rufo"
    review: "bundle exec rufo --check lib/"
    format: "bundle exec rufo lib/"

license_finder:
  skip_in_batch: true # Slow - run manually with: rvw license_finder
  name: License Finder
  description: Check dependency licenses for compliance
  tags: [dependencies, compliance, slow, dev]
  links:
    home: https://github.com/pivotal/LicenseFinder
  commands:
    install: "bundle exec gem install license_finder"
    review: "bundle exec license_finder --decisions-file=./dependency_decisions.yml"

notes:
  name: Notes
  description: Find TODO, FIXME, HACK, and OPTIMIZE comments
  tags: [quality, dev]
  commands:
    review: "grep -rn --include='*.rb' -E '(TODO|FIXME|HACK|OPTIMIZE|XXX):?' lib/ test/ || true"
  max_exit_status: 1
