bundle_audit:
  name: Bundle Audit
  description: Review Gem Dependencies for Security Issues
  tags: [critical, dependencies, ruby, dev]
  links:
    home: https://github.com/rubysec/bundler-audit
    install: https://github.com/rubysec/bundler-audit#install
  commands:
    install: 'bundle exec gem install bundler-audit'
    prepare: 'bundle exec bundle-audit update'
    review: 'bundle exec bundle-audit check --no-update'
    quiet_option: '--quiet'

tests:
  name: Minitest
  description: Unit Tests & Coverage
  tags: [ruby, tests, dev]
  links:
    home:
  commands:
    review: "bundle exec rake"
    quiet_option: '--silent'
  reports:
    open_on_fail: true
    local_file: coverage/index.html
    local_uri: 'file:///Users/garrettdimon/Code/reviewer/coverage/index.html#_AllFiles'
  env:
    testopts: --seed=$SEED --color
    coverage: true

reek:
  disabled: true
  name: Reek
  description: Examine Ruby Classes for Code Smells
  tags: [ruby, quality, dev]
  links:
    home: https://github.com/troessner/reek
    install: https://github.com/troessner/reek#quickstart
  commands:
    install: 'bundle exec gem install reek'
    review: 'bundle exec reek'
  flags:
    color:
    documentation:

flog:
  disabled: true # Flog provides guidance and is generally run solo
  name: Flog
  description: Reports your most tortured ruby code in an easy to read pain report.
  tags: [ruby, quality, dev]
  links:
    home: https://ruby.sadi.st/Flog.html
    install: https://ruby.sadi.st/Flog.html
  commands:
    install: 'bundle exec gem install flog'
    review: 'bundle exec flog -g lib'
  flags:
    threshold: 10 # Percentage. i.e. Show the most concerning 10% of results
    group:
    methods-only:

flay:
  disabled: true # Flay provides guidance and is generally run solo
  name: Flay
  description: Review ruby code for structural similarities and refactoring opportunities.
  tags: [ruby, quality, dev]
  links:
    home: https://ruby.sadi.st/Flay.html
    install: https://ruby.sadi.st/Flay.html
  commands:
    install: 'bundle exec gem install flay'
    review: 'bundle exec flay ./lib'
  flags:
    liberal:
    summary:


rubocop:
  name: Rubocop
  description: Review Ruby Syntax & Formatting for Consistency
  tags: [ruby, syntax]
  links:
    home: https://rubocop.org
    install: https://docs.rubocop.org/rubocop/1.13/installation.html
    ignore_syntax: https://docs.rubocop.org/rubocop/configuration.html#ignoredmethods
    disable_syntax: https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code
  commands:
    install: 'bundle exec gem install rubocop'
    review: 'bundle exec rubocop --parallel'
    format: 'bundle exec rubocop --auto-correct'
    quiet_option: '--format q'
  files:
    flag: ''
    separator: ' '
  flags:
    color:


# The YARD Parser can also come in handy:
#   https://yardoc.org/types
inch:
  tags: [docs, ruby, dev]
  name: Inch
  description: Review Ruby Documentation Quality
  links:
    home: https://rrrene.org/inch/
    usage: https://www.rubydoc.info/gems/yard/file/docs/Tags.md
  commands:
    install: 'bundle exec gem install inch'
    review: 'bundle exec inch'


yard:
  disabled: true
  tags: [docs, ruby, dev]
  name: Yard
  description: Generates Documentation
  links:
    home: https://yardoc.org
    usage: https://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md#using
    install: https://github.com/lsegal/yard#installing
  commands:
    install: 'bundle exec gem install yard'
    prepare: "yard doc 'lib/**/*.rb'"
    review: 'yard stats'
    serve: 'yard server --reload && open http://0.0.0.0:8808'
    generate:
    quiet_flag: '--quiet'


alex:
  disabled: true
  tags: [language, docs]
  name: Yard
  description: Generates Documentation
  links:
    home:
    usage:
    install:
  commands:
    install: 'yarn global add alex'
    review: 'alex .'
    quiet_flag: '--quiet'
