tests:
  name: Minitest
  description: Unit Tests
  tags: [ruby, tests]
  links:
    home:
  commands:
    review: 'bundle exec rake'
    quiet_flag: '--silent'

bundler_audit:
  tags: [critical, dependencies, ruby]
  name: Bundler Dependency Audit
  description: Check for Gem Security Issues
  links:
    home: https://github.com/rubysec/bundler-audit
    install: https://github.com/rubysec/bundler-audit#install
  commands:
    install: 'bundle exec gem install bundler-audit'
    prepare: 'bundle exec bundle-audit update'
    review: 'bundle exec bundle-audit check --no-update'
    quiet_flag: '--quiet'

rubocop:
  tags: [ruby, syntax]
  description: Review Ruby syntax/formatting for consistency
  links:
    home: https://rubocop.org
    install: https://docs.rubocop.org/rubocop/1.13/installation.html
    ignore_syntax: https://docs.rubocop.org/rubocop/configuration.html#ignoredmethods
    disable_syntax: https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code
  commands:
    install: 'bundle exec gem install rubocop'
    review: 'bundle exec rubocop --parallel'
    format: 'bundle exec rubocop --auto-correct'
    quiet_flag: '--format q'
