tests:
  name: Minitest
  description: Unit Tests
  tags: [ruby, tests]
  links:
    home:
  commands:
    review: 'bundle exec rake'
    quiet_flag: '--silent'

bundler_audit:
  tags: [dependencies, critical, ruby]
  name: Bundler Dependency Audit
  description: Check for Gem Security Issues
  links:
    home: https://github.com/rubysec/bundler-audit
    install: https://github.com/rubysec/bundler-audit#install
  commands:
    install: 'bundle exec gem install bundler-audit'
    prepare: 'bundle exec bundle-audit update'
    review: 'bundle exec bundle-audit check --no-update'
    quiet_flag: '--quiet'
