AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  UseCache: true
  CacheRootDirectory: './'
  Exclude:
    - 'bin/**/*'

# Let's aim for 80, but we don't need to be nagged if we judiciously go over.
Layout/LineLength:
  Enabled: false

# 10 is a good goal but a little draconian
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 15
