AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  UseCache: true
  CacheRootDirectory: './'
  Exclude:
    - 'bin/**/*'

# Let's aim for 80, but we don't need to be nagged if we judiciously go over.
Layout/LineLength:
  Enabled: false

# One case statement in a single method isn't complex.
Metrics/CyclomaticComplexity:
  AllowedMethods: ['case']

# Development dependencies in gemspec is fine for this gem
Gemspec/DevelopmentDependencies:
  Enabled: false

# Keyword arguments are self-documenting at call sites, so they don't
# create the readability problem that long positional lists do.
Metrics/ParameterLists:
  CountKeywordArgs: false

# The CLI entry point is a routing method with one guard clause per line.
# Each branch is a single method call — the structure is as clear as it gets.
Metrics/AbcSize:
  AllowedMethods: ['handle_early_exits']

# 10 is a good goal but a little draconian
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 15

# Test classes naturally grow with coverage (see test/.rubocop.yml for higher limit)
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 150

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 150

# Fasterer prefers yield over block.call for performance
Style/ExplicitBlockArgument:
  Enabled: false

# Fasterer prefers fetch with block over second argument for performance
Style/RedundantFetchBlock:
  Enabled: false
