AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  UseCache: true
  CacheRootDirectory: './'
  Exclude:
    - 'bin/**/*'

# Let's aim for 80, but we don't need to be nagged if we judiciously go over.
Layout/LineLength:
  Enabled: false

# One case statement in a single method isn't complex.
Metrics/CyclomaticComplexity:
  AllowedMethods: ['case']

# Development dependencies in gemspec is fine for this gem
Gemspec/DevelopmentDependencies:
  Enabled: false

# 10 is a good goal but a little draconian
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 15

# Fasterer prefers yield over block.call for performance
Style/ExplicitBlockArgument:
  Enabled: false

# Fasterer prefers fetch with block over second argument for performance
Style/RedundantFetchBlock:
  Enabled: false
